# version docker compose
version: '2.10.2'
services:
  elasticsearch:
    image: elasticsearch:8.4.1
    environment:
        # Un único nodo (no vamos a replicar la información)
        - discovery.type=single-node
        # Memoria minima y maxima
        - xpack.security.enabled=false
        - http.cors.allow-origin="*"
        - http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE
        - http.cors.enabled=true
        - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
        - http.cors.allow-credentials=true
    volumes:
        # Montamos le volumen de datos
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      # - target: 9200
      #   published: 9200
    networks:
      - elastic
    # Quitamos el límite de memoria del contenedor
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: kibana:8.4.1
    ports:
      - target: 5601
        published: 5601
    depends_on:
      - elasticsearch
    networks:
      - elastic      

volumes:
  es_data:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge